apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.272546634+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: a4c33a8ea7095911c57608e121eb208322da46941865624f7f8f2ab2fab75b33
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.260231797+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 380f3bcf4d61236d8baa25878ecb7cb79ddf9a87458cbb1511ed6a75dcb197fc
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.248652235+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 1132bcdf8bc1ed71fc6fbe2a227d5a63fc4d70a00c0595ae1c846c4dfc26e67f
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.365193485+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: c5746a37b9a6bcf4c5f9dee71d4b090e6cfe9e64320d64d7234e0cbb086ab5f2
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.352715788+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 5667043304c43b83d16d911adfd0e18fdf6a8bdbb71b2c5db8243ce4dc4b4407
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.340839309+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 61176b210c41b7f1153021924af204988fb50a0dbef2ed51856d5b98543078f7
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.324738981+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: f562da7744a44b335afdb6e027c3ac9795fa2eb8d8338e4836c11ac5e435a68d
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.316047566+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: fee17a98ae10f61fd1e3ac7819c7c1b77ffc40ef6cc36590cf5bdf6557f1284e
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.30772077+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 42d791cd4aae43adf19f0e8893aca197309163f55055c9140bdb0455d8bf2f9e
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.298436518+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 14547289cad3050e7494f8d82807fe4d816b0025ae9708082da4017f8cf3b6c1
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.288354519+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 2c2091d5eacc5738a7500dcfc6161cb73005a7479a1c22078c077e30fcf49d1e
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.237119519+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: bfc6135f6c542f18c1f3dae0ef05132585dfe37889d49cf5d365ea09afca4e75
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-05T15:21:20.221803846+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 66bc257b91877b02b0d68617bbd0daf4ff4ce6afe7ffeeba1e102ac70131bb13
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.13.0
    created: "2022-10-05T15:21:20.370693425+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 871e4726cd44dddc531dc9bcdbd4fb6e7da875fbe0c6ec347bfcda33acc2d246
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.9.5.tgz
    version: 10.9.5
  rabbitmq:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.9.16
    created: "2022-10-05T15:21:20.376508972+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: RabbitMQ is an open source general-purpose message broker that is
      designed for consistent, highly-available messaging scenarios (both synchronous
      and asynchronous).
    digest: e87eafdbe989aecc9e6dd4a9190b0fa616591b26004a760a5c4ef4d4f4dbb0fd
    home: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
    keywords:
    - rabbitmq
    - message queue
    - AMQP
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: rabbitmq
    sources:
    - https://github.com/bitnami/bitnami-docker-rabbitmq
    - https://www.rabbitmq.com
    urls:
    - charts/rabbitmq-9.0.1.tgz
    version: 9.0.1
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.5
    created: "2022-10-05T15:21:20.383489656+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: f8fa3b0bdaecf7f9aa1669b027c5452f7efaab21c10b0dbcf7148e17c54ac5b7
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-15.3.2.tgz
    version: 15.3.2
generated: "2022-10-05T15:21:20.20797147+02:00"
