apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-13T15:17:04.163237045+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 2f697dcc0bfea166c021a18bc07ef0d47e56eb879421b6571d4625111ff01394
    name: commonground-gateway
    type: application
    urls:
    - commonground-gateway-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.13.0
    created: "2021-10-13T15:17:04.170955789+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 871e4726cd44dddc531dc9bcdbd4fb6e7da875fbe0c6ec347bfcda33acc2d246
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.9.5.tgz
    version: 10.9.5
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.5
    created: "2021-10-13T15:17:04.179551551+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: f8fa3b0bdaecf7f9aa1669b027c5452f7efaab21c10b0dbcf7148e17c54ac5b7
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-15.3.2.tgz
    version: 15.3.2
generated: "2021-10-13T15:17:04.149209907+02:00"
