apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commonground-gateway.fullname" . }}
  labels:
    {{- include "commonground-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "commonground-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "commonground-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "commonground-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: dependencies
          secret:
            secretName: {{ include "commonground-gateway.fullname" . }}-dependencies
            defaultMode: 420
        - name: app-certificates
          secret:
            {{ if .Values.security.certificate.existingSecret }}
            secretName: {{ .Values.security.certificate.existingSecret }}
            {{ else }}
            secretName: {{ include "commonground-gateway.fullname" . }}-certificate
            {{ end }}
            defaultMode: 420
        {{- if .Values.security.saml.enabled }}
        - name: idp-certificate
          secret:
            {{ if .Values.security.saml.idp.certificate.existingSecret }}
            secretName: {{ .Values.security.saml.idp.certificate.existingSecret }}
            {{ else }}
            secretName: {{ include "commonground-gateway.fullname" . }}-idpcertificate
            {{ end }}
            defaultMode: 420
        {{- end }}
        {{- if .Values.fixtures }}
        - name: fixtures
          configMap:
            name: {{ include "commonground-gateway.fullname" . }}-fixtures
            defaultMode: 420
        {{- end }}

      containers:
        - name: {{ include "commonground-gateway.fullname" . }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /srv/api/config/packages/dependencies.yaml
              subPath: dependencies.yaml
              name: dependencies
              readOnly: true
            - mountPath: /var/run/certs
              name: app-certificates
              readOnly: true
            {{- if .Values.security.saml.enabled }}
            - mountPath: /var/run/idp
              name: idp-certificate
              readOnly: true
            {{- end }}
            {{- if .Values.fixtures }}
            - mountPath: /srv/api/fixtures
              name: fixtures
              readOnly: true
            {{- end }}
          env:
            - name: APP_ENV
              value: {{ .Values.config.env }}
            - name: AUTH_ENABLED
              value: 'true'
            - name: APP_REPRO
              value: 'https://github.com/ConductionNL/commonground-gateway'
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: trusted-hosts
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  key: trusted-proxies
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  key: app-cors-allow-origin
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: app-version
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: APP_CACHE
              valueFrom:
                configMapKeyRef:
                  key: cache
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ include "commonground-gateway.fullname" . }}
            {{- if or (and .Values.security.certificate.certificate .Values.security.certificate.privateKey) .Values.security.certificate.existingSecret }}
            - name: APP_CERT
              value: '/var/run/certs/tls.crt'
            - name: APP_KEY
              value: '/var/run/certs/tls.key'
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis-host
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: redis-port
                  name: {{ include "commonground-gateway.fullname" . }}
            {{- end }}
            - name: SAML_ENABLED
              valueFrom:
                secretKeyRef:
                  key: saml-enabled
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: DIGID_ENABLED
              valueFrom:
                secretKeyRef:
                  key: digid-enabled
                  name: {{ include "commonground-gateway.fullname" . }}
            {{- if .Values.security.saml.enabled }}
            - name: SAML_METADATA_LOCATION
              valueFrom:
                secretKeyRef:
                  key: saml-metadata-location
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: SAML_SIGN_ON_URL
              valueFrom:
                secretKeyRef:
                  key: saml-single-sign-on-url
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: SAML_LOGOUT_URL
              valueFrom:
                secretKeyRef:
                  key: saml-logout-url
                  name: {{ include "commonground-gateway.fullname" . }}
            - name: SAML_IDP_CERT
              value: '/var/run/idp/idp.crt'
            {{- end }}
            {{- if .Values.security.digid.enabled }}
            - name: DIGID_METADATA_LOCATION
              valueFrom:
                  secretKeyRef:
                      key: digid-metadata-location
                      name: {{ include "commonground-gateway.fullname" . }}
            - name: DIGID_SIGN_ON_URL
              valueFrom:
                  secretKeyRef:
                      key: digid-single-sign-on-url
                      name: {{ include "commonground-gateway.fullname" . }}
            - name: DIGID_LOGOUT_URL
              valueFrom:
                  secretKeyRef:
                      key: digid-logout-url
                      name: {{ include "commonground-gateway.fullname" . }}
            - name: DIGID_IDP_CERT
              value: '/var/run/idp/digid_idp.crt'
            {{- end }}
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
        - name: {{ include "commonground-gateway.fullname" . }}-nginx
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          env:
            - name: PHP_SERVICE
              value: localhost
            - name: NGINX_HOST
              value: localhost
            - name: BACKENDS
              value: localhost
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
