{{- if .Values.config.samesiteCookie }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commonground-gateway.fullname" . }}-framework
  labels:
    {{- include "commonground-gateway.labels" . | nindent 4 }}
data:
    framework.yaml: |
        # see https://symfony.com/doc/current/reference/configuration/framework.html
        framework:
            session:
                handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
                cookie_secure: true
                cookie_samesite: {{ .Values.config.samesiteCookie }}
                storage_factory_id: session.storage.factory.native
        parameters:
            samesite: {{ .Values.config.samesiteCookie }}
{{- end }}
