{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commonground-gateway.fullname" . }}
  labels:
  {{- include "commonground-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=11" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  {{- if .Values.security.saml.enabled }}
  saml-metadata-location: {{ .Values.security.saml.idp.metadata | b64enc | quote }}
  saml-single-sign-on-url: {{ .Values.security.saml.idp.singleSignOnUrl | b64enc | quote }}
  saml-logout-url: {{ .Values.security.saml.idp.logoutUrl | b64enc | quote }}
  {{- end }}
  saml-enabled: {{ .Values.security.saml.enabled | toString | b64enc | quote }}
  {{- if .Values.security.digid.enabled }}
  digid-metadata-location: {{ .Values.security.digid.idp.metadata | b64enc | quote }}
  digid-single-sign-on-url: {{ .Values.security.digid.idp.singleSignOnUrl | b64enc | quote }}
  digid-logout-url: {{ .Values.security.digid.idp.logoutUrl | b64enc | quote }}
  {{- end }}
  digid-enabled: {{ .Values.security.digid.enabled | toString | b64enc | quote }}
