{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
{{- $mongodbServiceName := include "mongodb.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commonground-gateway.fullname" . }}
  labels:
  {{- include "commonground-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=11" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  {{- if .Values.security.saml.enabled }}
  saml-metadata-location: {{ .Values.security.saml.idp.metadata | b64enc | quote }}
  saml-single-sign-on-url: {{ .Values.security.saml.idp.singleSignOnUrl | b64enc | quote }}
  saml-logout-url: {{ .Values.security.saml.idp.logoutUrl | b64enc | quote }}
  {{- end }}
  saml-enabled: {{ .Values.security.saml.enabled | toString | b64enc | quote }}
  {{- if .Values.security.digid.enabled }}
  digid-metadata-location: {{ .Values.security.digid.idp.metadata | b64enc | quote }}
  digid-single-sign-on-url: {{ .Values.security.digid.idp.singleSignOnUrl | b64enc | quote }}
  digid-logout-url: {{ .Values.security.digid.idp.logoutUrl | b64enc | quote }}
  digid-artifact-url: {{ .Values.security.digid.artifactUrl | b64enc | quote }}
  {{- end }}
  digid-enabled: {{ .Values.security.digid.enabled | toString | b64enc | quote }}
  {{-  if and .Values.security.digid.certificate .Values.security.digid.privateKey }}
  digid-certificate: {{.Values.security.digid.certificate | b64enc | quote }}
  digid-privatekey: {{ .Values.security.digid.privateKey | b64enc | quote }}
  {{- end }}
  githubKey: {{ .Values.config.githubKey | b64enc | quote }}

  rabbitmq-username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
    
  {{ if .Values.mongodb.enabled }}
  mongodb-url: {{ printf "mongodb://%s:%s@%s" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword $mongodbServiceName | b64enc | quote }}
  {{ else }}
  mongodb-url: {{ .Values.mongodb.url | b64enc | quote }}
  {{ end }}
